---
title: "Density Plots - 2018 Regular Season Pass Locations, League-Wide and by Quarterback"
output:
  pdf_document: default
---

```{r setup, include=FALSE, warning = FALSE, message = FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(MASS)
library(tidyverse)
library(mgcv)
```

```{r}
pass_df <- read.csv("../pass_and_game_data.csv")
passes <- subset(pass_df, !(is.na(x)) & type == "reg")

passes <- passes %>%
  mutate(is_complete = 
           ifelse(pass_type %in% c("COMPLETE", "TOUCHDOWN"), 1, 0),
         is_incomplete = 
           ifelse(pass_type %in% c("COMPLETE", "TOUCHDOWN"), 0, 1)
         )

complete <- subset(passes, pass_type %in% c("COMPLETE", "TOUCHDOWN"))
incomplete <- subset(passes, pass_type %in% c("INCOMPLETE", "INTERCEPTION"))

passes_18 <- subset(passes, season == 2018)
complete_18 <- subset(complete, season == 2018)
incomplete_18 <- subset(incomplete, season == 2018)
```



# Initial Scatterplots of Pass Locations

```{r}
ggplot(data = complete_18, aes(x = x, y = y, color = pass_type)) +
  geom_point(size = 0.5) +
  scale_color_manual(values = c("green", "blue"), "Pass Type") +
  geom_hline(color = "blue", yintercept = 0) +
  annotate("text", -30, 0, vjust = -0.5, label = "LOS") +
  theme_bw() +
  labs(title = "League-Wide Locations of Complete Passes in 2018",
       x = "Field Width", y = "Field Length")
```

```{r}
ggplot(data = incomplete, aes(x = x, y = y, color = pass_type)) +
  geom_point(size = 0.5) +
  scale_color_manual(values = c("gray", "red"), "Pass Type") +
  geom_hline(color = "blue", yintercept = 0) +
  annotate("text", -30, 0, vjust = -0.5, label = "LOS") +
  theme_bw() +
  labs(title = "League-Wide Locations of Incomplete Passes in 2018",
       x = "Field Width", y = "Field Length")
```


# 2018 Complete Pass Density Plots

```{r}
complete_18_kde <- kde2d(complete_18$x, complete_18$y, h = c(5, 5))

complete_18_grid <- data.frame(with(complete_18_kde, expand.grid(x,y)), as.vector(complete_18_kde$z))
names(complete_18_grid) <- c("x", "y", "z")

complete_18_model <- gam(z ~ s(x, y), data = complete_18_grid)

complete_18$dens <- predict(complete_18_model, newdata = data.frame(x = complete_18$x, y = complete_18$y))
```

```{r}
ggplot(complete_18, aes(x = x, y = y, color = dens)) + 
  geom_point() + 
  scale_color_gradient2(low = "darkred", high = "darkblue", mid = "white", midpoint = 0.0006) +
  labs(title = "Kernel Density Estimate of Complete Pass Locations in 2018",
       x = "Field Width", y = "Field Length",
       color = "Density", fill = "KDE\nLevel")
```

```{r}
ggplot(complete_18, aes(x = x, y = y, color = dens)) + 
  stat_density_2d(aes(fill = ..density..), geom = "raster", contour = FALSE,
                 h = c(5, 5)) +
  scale_fill_gradient2(low = "darkred", high = "darkblue", mid = "white", midpoint = 0.0006) +
  labs(title = "Kernel Density Estimate of Complete Pass Locations in 2018",
       x = "Field Width", y = "Field Length",
       color = "Density", fill = "KDE\nLevel")
```


```{r}
is_complete_18_model <- gam(is_complete ~ s(x, y), data = passes_18)

a <- seq(-30, 30, length.out = 30--30+1)
b <- seq(-10, 55, length.out = 55--10+1)

complete_18_predict_data <- data.frame(x = c(outer(a, b * 0 + 1)), y = c(outer(a * 0 + 1, b)))

complete_18_pass_preds <- predict(is_complete_18_model, complete_18_predict_data)
complete_18_predict_data <- complete_18_predict_data %>% 
  mutate(pass_prob = complete_18_pass_preds / (1 + exp(complete_18_pass_preds)))
```

```{r}
ggplot(complete_18_predict_data) +
  geom_tile(aes(x = x, y = y, fill = pass_prob)) +
  scale_fill_gradient2(low = "darkred", high = "darkblue", mid = "white", midpoint = 0.16) +
  coord_fixed() +
  theme_bw() +
  labs(title = "Probability of a Pass being Complete by Location in 2018",
       x = "Field Width", y = "Field Length",
       fill = "Probability")
```


# Quarterbacks with at least 100 passes in 2018 Regular Season, sorted from least to most total passes


```{r}
qb_names_18 <- names(which(sort(table(complete_18$name)) >= 100))

for (qb_name in qb_names_18) {

  qb_passes <- subset(passes_18, name == qb_name)
  qb_complete <- subset(complete_18, name == qb_name)
  team <- qb_complete[1,]$team
  cap <- paste("Total Passes =", nrow(qb_complete))

  gg_complete <- ggplot(data = qb_complete, aes(x = x, y = y)) +
    geom_point(aes(color = pass_type), size = 0.5) +
    scale_color_manual(values = c("green", "blue"), "Pass Type") +
    geom_hline(color = "blue", yintercept = 0) +
    annotate("text", -30, 0, vjust = -0.5, label = "LOS") +
    theme_bw() +
    labs(x = "Field Width", y = "Field Length",
         caption = cap) +
    ggtitle(paste("Complete Passes:\n", qb_name, " (", team,  ") in 2018", sep = "")) 
  print(gg_complete)
  
  qb_kde <- kde2d(complete_18$x, complete_18$y, h = c(5, 5))
  qb_grid <- data.frame(with(qb_kde, expand.grid(x,y)), as.vector(qb_kde$z))
  names(qb_grid) <- c("x", "y", "z")
  qb_model <- gam(z ~ s(x, y), data = qb_grid)
  qb_complete$dens <- predict(qb_model, newdata = data.frame(x = qb_complete$x, y = qb_complete$y))
  
  # qb_dens_scatter <- ggplot(qb_complete, aes(x = x, y = y, color = dens)) + 
  #   geom_point() + 
  #   scale_color_gradient2(low = "darkred", high = "darkblue", mid = "white", midpoint = 0.0006) +
  #   labs(x = "Field Width", y = "Field Length",
  #      color = "Density", fill = "KDE\nLevel") +
  #   ggtitle(paste("Complete Passes Density:\n", qb_name, "in 2018"))
  # print(qb_dens_scatter)
  median <-  median(qb_complete$dens)
  qb_dens <- ggplot(qb_complete, aes(x = x, y = y, color = dens)) + 
    stat_density_2d(aes(fill = ..density..), geom = "raster", contour = FALSE,
                 h = c(7.5, 7.5)) + 
    scale_fill_gradient2(low = "darkred", high = "darkblue", mid = "white", midpoint = median) +
    labs(x = "Field Width", y = "Field Length",
       color = "Density", fill = "KDE\nLevel", 
       caption = cap) +
    geom_hline(color = "blue", yintercept = 0) +
    annotate("text", -30, 0, vjust = -0.5, label = "LOS") +
    ggtitle(paste("Complete Passes Density:\n", qb_name, " (", team,  ") in 2018", sep = "")) 
  print(qb_dens)
}
```








